# =============================================================================
# Arquivo Docker Compose para Inicialização (compose-init.yml)
#
# Propósito:
#   Este arquivo define APENAS o serviço 'init', que é responsável por
#   gerar o arquivo principal 'docker-compose.yml' e baixar as dependências.
#
# Como Usar:
#   docker compose -f compose-init.yml run --rm init
# =============================================================================

version: '3.8'

services:
  init:
    # 1. Faz build de um stage 'init' no Dockerfile que contenha bash, envsubst, curl, wget, etc.
    build:
      # Define o contexto de build como o diretório atual.
      context: .
      # Define o Dockerfile a ser usado para construir a imagem.
      dockerfile: ./docker/Dockerfile
      target: init
    image: spark-hadoop-init:latest
    container_name: spark_hadoop_init

    # 2. Monta todo o repositório dentro do container, para que scripts/* e config_files/* fiquem disponíveis
    volumes:
      - ./:/app:rw

    # 3. Carrega variáveis de ambiente
    env_file:
      - .env.template
      - .env

    # 4. Injeta a senha como secret, disponível em /run/secrets/user_password
    secrets:
      - user_password

    environment:
      - DOCKER_COMPOSE_RUN=true
      - PASSWORD_FILE=/run/secrets/user_password
    
    # 5. Permite logs interativos
    tty: true
    stdin_open: true

    # 6. Executa o nosso init.sh
    command: ["bash", "/app/scripts/init.sh"]

secrets:
  user_password:
    file: .password

